### ISSUE TITLE
Push new release to crates.io?

### ISSUE THREAD

**Issue by fuchsnj** [stm32-rs/stm32f1xx-hal#162]
I just spent some time cloning this repo and making a change, only to find out it was already implemented (https://github.com/stm32-rs/stm32f1xx-hal/pull/160). Partially my fault, I didn't find an open issue for it so I started working on it.

Is there any reason that change hasn't been released on crates.io?

I also noticed crates.io has a later version (0.5.2) than master (0.5.1) in the Cargo.toml. (It was updated in the README though).

**Comment by TheZoq2** [comment]
Hi.

There is no particular reason for it not being released, I just haven't gotten around to it. I'll do it tonight if I remember.

And the 0.5.2/0.5.1 issue is probably me forgetting to run `git push upstram` after doing the release. Also, 0.5.2 is just 0.5.1 with some minor doc fixes because I messed up the release :wink:

**Comment by TheZoq2** [comment]
`v0.5.3` has been released :tada:

**Comment by fuchsnj** [comment]
thanks!
