### ISSUE TITLE
SPI doesn't support 16bit data frames

### ISSUE THREAD

**Issue by jonnyando** [stm32-rs/stm32f1xx-hal#256]
It looks like the device spi peripherals are initialised with the DFF bit in CR1 cleared, setting the peripheral to 8bit mode. Additionally, blocking::spi::Write, FullDuplex, and Transfer::Default are all only implemented for `<u8>`. Does it make sense to also implement these functions for a 16 bit data frame mode?

Simply implementing a `<u16>` version of these functions wouldn't work as the peripheral would need to know what mode it is in and ensure CR1 is configured correctly.

I'm still new to rust, so don't know where to start on this. Any ideas on how to add this functionality, or whether it is a good addition or not?

**Comment by TheZoq2** [comment]
I see no reason not to implement them. The reason they're not here yet is simply because noone has done it so far.

As you said, some trickery is required.

The simplest way to do so would be to just duplicate the structs, and replace the dataframe size, but we probably want to reduce code duplication.

I think there may be two ways to make it nicer. One is to make most of the current code generic over the type returned, so you would have `Spi1<..., DataFrame>`. Then we would have to add a few functions for the specific dataframe, probably with a separate trait

```rust
impl SpiInternal for Spi1<..., u8> {
    fn setup_data_frame() {
        ...
    }
    fn read_value() -> u8 {
        ...
    }
}
```
Those functions would then be used by the main impl

Another option is to try and move most of the generic impl into free standing functions, and have some thin impl blocks for the different word lengths.

I'm leaning towards the second being nicer, but I'm not sure.

If you want to have a go at implementing this, let me know, I'll gladly help you out if you get stuck!
```
