### ISSUE TITLE
Reenable DMA

### ISSUE THREAD

**Issue by jamwaffles** [stm32-rs/stm32f1xx-hal#38]
DMA was disabled in bae2a2c65c1fdddc6df981a002f455fb232ef611 (by @therealprof), but with no explanation as to why. Can it be reenabled? Does it need some work to get running again? 

I'm happy to try getting it working again, but I have very little experience with DMA.

**Comment by therealprof** [comment]
DMA was disabled because the previous experimental implementation does not work on stable (which was the main goal for publication). I think it'll require a bit of rework to make it compile (and work) with stable.

If you can make it work that'd be really cool, though in order to be really useful (e.g. for display drivers) we might have to think about amending the `embedded-hal` traits as well.

**Comment by TeXitoi** [comment]
https://docs.rust-embedded.org/embedonomicon/dma.html must also be a great reading to resurect DMA (I didn't read it yet).

**Comment by jamwaffles** [comment]
Thanks for the explanation and docs links, I'll attempt some implementation when I have some spare time :slightly_smiling_face:

**Comment by ssendev** [comment]
If I read the Changelog right this can be closed since is it was re-enabled

**Comment by TheZoq2** [comment]
Yes, that looks correct. Thanks for the reminder :)
